# Generated by Django 4.1.2 on 2022-12-10 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookdetails",
            name="collections",
            field=models.CharField(
                default="", max_length=255, primary_key=True, serialize=False
            ),
        ),
    ]
