# Generated by Django 4.1.2 on 2022-12-07 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="books",
            name="book_author",
        ),
        migrations.RemoveField(
            model_name="books",
            name="isbn",
        ),
        migrations.RemoveField(
            model_name="books",
            name="publication_year",
        ),
    ]
