# Generated by Django 4.1.2 on 2022-11-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="detail",
            name="id",
        ),
        migrations.AlterField(
            model_name="detail",
            name="matricno",
            field=models.CharField(
                default="", max_length=9, primary_key=True, serialize=False
            ),
        ),
    ]
