# Generated by Django 4.1.2 on 2022-12-10 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_bookdetails_collections"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookdetails",
            name="collections",
            field=models.CharField(
                choices=[
                    ("fiction", "Fiction"),
                    ("non-fiction", "Non-Fiction"),
                    ("autobiography", "Autobiography"),
                    ("biography", "Biography"),
                ],
                default="",
                max_length=255,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
