# Generated by Django 4.1.2 on 2022-12-13 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_user_follower"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="genre",
            options={"verbose_name_plural": "Genres"},
        ),
        migrations.AlterField(
            model_name="books",
            name="genre",
            field=models.OneToOneField(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.genre",
            ),
        ),
    ]
