# Generated by Django 4.1.2 on 2022-11-21 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_delete_customuser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="detail",
            name="about",
        ),
        migrations.RemoveField(
            model_name="detail",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="detail",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="detail",
            name="middle_name",
        ),
        migrations.AddField(
            model_name="detail",
            name="user",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
