# Generated by Django 4.1.2 on 2022-11-07 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_register_dob"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="register",
            name="dob",
        ),
        migrations.RemoveField(
            model_name="register",
            name="gender",
        ),
    ]
