# Generated by Django 4.1.2 on 2022-11-29 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_detail_id_alter_detail_matricno"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "image",
                    models.ImageField(default="user_avatar.png", upload_to="..."),
                ),
                (
                    "last_visit",
                    models.DateField(blank=True, default=django.utils.timezone.now),
                ),
                ("location", models.CharField(blank=True, max_length=254, null=True)),
                ("contact_phone", models.CharField(max_length=15)),
                (
                    "user_role",
                    models.CharField(
                        choices=[
                            ("customer", "Customer"),
                            ("support", "Support"),
                            ("admin", "Admin"),
                        ],
                        default="customer",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
