# Generated by Django 4.1.2 on 2022-12-13 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_genre_options_alter_books_genre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="books",
            name="genre",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.genre",
            ),
        ),
    ]
