# Generated by Django 4.1.2 on 2022-11-29 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_profile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
