# Generated by Django 4.1.2 on 2022-11-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_detail_about_remove_detail_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="detail",
            name="description",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="detail",
            name="title",
            field=models.CharField(default="", max_length=200),
        ),
    ]
