# Generated by Django 4.1.2 on 2022-11-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_register_dob_remove_register_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="register",
            name="dob",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="register",
            name="gender",
            field=models.CharField(
                choices=[
                    ("MALE", "Male"),
                    ("FEMALE", "Female"),
                    ("OTHERS", "Prefer not to say"),
                ],
                default="",
                max_length=255,
                null=True,
            ),
        ),
    ]
