# Generated by Django 4.1.2 on 2022-12-02 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_delete_profile"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Detail",
            new_name="UserProfile",
        ),
    ]
