# Generated by Django 4.1.2 on 2023-01-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_borrowedbook_book_alter_borrowedbook_member_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="library_no",
            field=models.CharField(default="", max_length=15, null=True),
        ),
    ]
