# Generated by Django 4.1.2 on 2022-11-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_register_dob_register_gender"),
    ]

    operations = [
        migrations.CreateModel(
            name="Details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(default="", max_length=255)),
                ("last_name", models.CharField(default="", max_length=255)),
                ("middle_name", models.CharField(default="", max_length=255)),
                ("about", models.TextField(default="", max_length=255)),
            ],
        ),
    ]
