# Generated by Django 4.1.2 on 2022-12-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_books_genre"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalog",
            name="catalog_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="collection",
            name="collection_name",
            field=models.CharField(default="", max_length=255),
        ),
    ]
