# Generated by Django 4.1.2 on 2022-11-22 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_detail_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="detail",
            name="email",
            field=models.EmailField(default="", max_length=254),
        ),
    ]
