# Generated by Django 4.1.2 on 2023-01-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_library_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="library_no",
            field=models.CharField(blank=True, default="", max_length=15),
        ),
    ]
