# Generated by Django 4.1.2 on 2022-11-18 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_details"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Details",
            new_name="Detail",
        ),
    ]
