# Generated by Django 4.1.2 on 2022-12-14 12:28

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_catalog_catalog_name_collection_collection_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="profile_picture",
        ),
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.FileField(
                blank=True,
                default="",
                null=True,
                upload_to="images",
                validators=[accounts.models.validate_pic_extension],
            ),
        ),
    ]
