# Generated by Django 4.1.2 on 2022-11-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_rename_user_detail_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="detail",
            name="matricno",
            field=models.CharField(default="", max_length=9),
        ),
    ]
