# Generated by Django 4.1.2 on 2022-12-14 12:41

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_remove_userprofile_profile_picture_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="",
                null=True,
                upload_to="images",
                validators=[accounts.models.validate_pic_extension],
            ),
        ),
    ]
