# Generated by Django 4.1.2 on 2023-01-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_user_library_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="borrowbook",
            name="library_no",
            field=models.CharField(blank=True, default="", max_length=15),
        ),
    ]
