# Generated by Django 4.1.2 on 2022-12-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_user_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password2",
            field=models.CharField(default="", max_length=255),
        ),
    ]
