# Generated by Django 4.1.2 on 2022-11-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_detail_matricno"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="detail",
            name="id",
        ),
        migrations.AlterField(
            model_name="detail",
            name="matricno",
            field=models.CharField(
                default="", max_length=9, primary_key=True, serialize=False
            ),
        ),
    ]
