# Generated by Django 4.1.2 on 2022-12-04 13:16

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_userprofile_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="",
                null=True,
                upload_to="static/img",
                validators=[accounts.models.validate_file_extension],
            ),
        ),
    ]
