# Generated by Django 4.1.2 on 2022-12-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_user_password2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password2",
            field=models.CharField(
                default="", max_length=255, verbose_name="Confirm Password"
            ),
        ),
    ]
