# Generated by Django 4.1.2 on 2022-12-14 13:02

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_alter_user_password2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password2",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                null=True,
                verbose_name="Confirm Password",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="",
                null=True,
                upload_to="images",
                validators=[accounts.models.validate_pic_extension],
            ),
        ),
    ]
