# Generated by Django 4.1.2 on 2023-01-07 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_alter_user_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="Idk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=128)),
            ],
        ),
    ]
