# Generated by Django 4.1.2 on 2022-12-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_alter_user_password2_alter_user_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password2",
            field=models.CharField(
                blank=True,
                default="",
                max_length=128,
                null=True,
                verbose_name="Confirm Password",
            ),
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
