# Generated by Django 4.1.2 on 2023-01-08 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_idk"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="student",
            field=models.BooleanField(default=False),
        ),
    ]
