# Generated by Django 4.1.2 on 2023-01-08 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_user_staff_user_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="staff",
            field=models.CharField(
                choices=[("Staff", "Staff")], default="", max_length=255
            ),
        ),
    ]
