# Generated by Django 4.1.2 on 2023-01-08 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_alter_user_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="staff",
            field=models.CharField(
                choices=[("", ""), ("Staff", "Staff")], default="", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="student",
            field=models.CharField(
                choices=[("", ""), ("Staff", "Staff")], default="", max_length=255
            ),
        ),
    ]
