# Generated by Django 4.1.2 on 2023-01-08 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_alter_user_staff_alter_user_student"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="student",
        ),
        migrations.AlterField(
            model_name="user",
            name="staff",
            field=models.CharField(
                choices=[("Staff", "Staff"), ("Student", "Student")],
                default="",
                max_length=255,
                null=True,
            ),
        ),
    ]
