# Generated by Django 4.1.2 on 2023-01-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_user_student_alter_user_staff"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="staff",
        ),
        migrations.RemoveField(
            model_name="user",
            name="student",
        ),
        migrations.AddField(
            model_name="user",
            name="designation",
            field=models.CharField(
                choices=[("Staff", "Staff"), ("Student", "Student")],
                default="",
                max_length=255,
            ),
        ),
    ]
