# Generated by Django 4.1.2 on 2023-01-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_remove_user_staff_remove_user_student_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="designation",
        ),
        migrations.AddField(
            model_name="user",
            name="staff",
            field=models.BooleanField(default=False),
        ),
    ]
