# Generated by Django 4.1.2 on 2023-01-08 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_remove_user_designation_user_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="student",
            field=models.BooleanField(default=False),
        ),
    ]
