# Generated by Django 4.1.2 on 2023-01-08 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0021_user_student"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="staff",
        ),
        migrations.RemoveField(
            model_name="user",
            name="student",
        ),
    ]
