# Generated by Django 4.1.2 on 2023-01-08 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0022_remove_user_staff_remove_user_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="designation",
            field=models.CharField(
                blank=True,
                choices=[("Staff", "Staff"), ("Student", "Student")],
                default="",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="library_id",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                null=True,
                verbose_name="Library Card Id",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="matric_no",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                null=True,
                verbose_name="Matric Number",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="staff_id",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                null=True,
                verbose_name="Staff Id",
            ),
        ),
    ]
