# Generated by Django 4.1.2 on 2023-01-08 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0023_user_designation_user_library_id_user_matric_no_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="lib_user",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                null=True,
                verbose_name="Library User",
            ),
        ),
    ]
