# Generated by Django 4.1.2 on 2023-01-08 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0024_user_lib_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="lib_user",
            field=models.CharField(
                blank=True,
                choices=[("Yes", "Yes"), ("No", "No")],
                default="",
                max_length=255,
                null=True,
                verbose_name="Library User",
            ),
        ),
    ]
